name: Debashmita Poddar
markdown: kramdown
permalink: /blog/:categories/:title


plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'